### ISSUE TITLE
Russian quote marks and formatting

### ISSUE THREAD

**Issue by ForNeVeR** [procxx/tdesktop#13]
### Steps to reproduce
1. Write the text `(**x** y z)` in chat ⇒ it formats the `x` in bold (OK).
2. Write the same text with Russian quote marks `«**x** y z»` ⇒ it doesn't format the bold text and leaves `*` as is (FAIL).

See upstream issue https://github.com/telegramdesktop/tdesktop/issues/3867 for list of additional characters.

### Expected behaviour
The Russian quote marks should be considered the same as ordinary braces in context of formatting. `x` should be bold in both samples.

### Actual behaviour
Russian quote marks considered as ordinary text, formatting doesn't work.

### Configuration
**Operating system:** Windows 8.1
**Version of Telegram Desktop:** 1.1.23

**Comment by crackedmind** [comment]
@ForNeVeR

**Comment by ForNeVeR** [comment]
Fixed in upstream: https://github.com/telegramdesktop/tdesktop/commit/2e421e8aede67a73e2901137a2a44544fa26d3b7
