### ISSUE TITLE
Optional message formatting

### ISSUE THREAD

**Issue by ForNeVeR** [procxx/tdesktop#132]
Currently, Kepka unconditionally turns every `<<` into `«` etc. This is mostly ridiculous and rarely useful.

I suggest porting this PR from the upstream: https://github.com/telegramdesktop/tdesktop/pull/4553/

**Comment by berkus** [comment]
I suggest we remove this really dumb text-replacer, and add instead something more advanced like [Typografica](https://wackowiki.org/doc/Dev/Projects/Typografica). Then make this enable switch turn on and off the Typografica engine.
