### ISSUE TITLE
Fix Windows 32-bit support

### ISSUE THREAD

**Issue by crackedmind** [procxx/tdesktop#17]
(For clarifying the comments: The title was "Drop windows 32 bit support" - leha-bot)

**Comment by mymedia2** [comment]
Please do not do it. There are still many 32-bit computers, some of them even incompatible with x86. Ideally, code should not depend on bitness of machine.

**Comment by ForNeVeR** [comment]
@mymedia2 please note that we were talking about Windows x32 support here.

**Comment by Hexawolf** [comment]
I think there's much more machines running amd64 processor but 32-bit OS on Windows than on Linux. If this issue doesn't gets in the way of development then there's no reason for that.
