### ISSUE TITLE
Allow to change file download location

### ISSUE THREAD

**Issue by ForNeVeR** [procxx/tdesktop#26]
Currently, the file download location is hardcoded (at least on Windows) to `~/Downloads/Telegram Desktop/`. I suggest it should be possible to change in the settings.

**Comment by crackedmind** [comment]
This settings was already presented 
![image](https://user-images.githubusercontent.com/1381503/33589985-4e39909c-d98d-11e7-8e9f-a3f9f29c876b.png)

**Comment by ForNeVeR** [comment]
Wow, alright!
