### ISSUE TITLE
Backport OpenSSL 1.1 patches from upstream

### ISSUE THREAD

**Issue by xvitaly** [procxx/tdesktop#33]
We need to backport this three commits:
1. https://github.com/telegramdesktop/tdesktop/commit/93809ec404a9d31565cd3be3eef94ceb5f6e3aee
2. https://github.com/telegramdesktop/tdesktop/commit/f813bb704f4eab542640517716bd14257c5a707f
3. https://github.com/telegramdesktop/tdesktop/commit/007ab3b7b89a0dddc5d957162bc2093f02063d21

**Comment by berkus** [comment]
Aye aye, on it.
