### ISSUE TITLE
Appveyor Level Up

### ISSUE THREAD

**Issue by ForNeVeR** [procxx/tdesktop#57]
- [x] build only `RelWithDebInfo` on Appveyor
- [x] pack it without PDB
- [x] pack PDBs into a separate archive
- [x] run `ctest` (`ctest .`, see on Travis)
- [x] publish `Release` to GitHub releases (see [this](https://github.com/matwey/fips3/blob/60c1bfd5d6cee9bced17fe5b19347c5be9cffa8e/.appveyor.yml#L32-L43) as an example)

**Comment by berkus** [comment]
Latest developments:

- On Travis we are building only `RelWithDebInfo` build, lets do the same for AppVeyor.

(i.e. publish it too, but need to **not** package the PDB files to final distro zip)

**Comment by ForNeVeR** [comment]
@berkus why don't publish PDB?

**Comment by berkus** [comment]
I didn't say "don't publish"

I said not package it into the installer ZIP file.

Publish PDB as separate artifact for debugging.
