### ISSUE TITLE
Use different profile directory

### ISSUE THREAD

**Issue by ghost** [procxx/tdesktop#71]
Telegram Desktop wipes profile on Linux when it detects created profile with newer version. Kepka forked from 1.1.x tdesktop, so profile gets wiped when I launch it after using upstream.

My suggestion is to change profile directory to kepka-specific: `~/.local/share/Kepka`.

**Comment by ghost** [comment]
https://github.com/procxx/kepka/blob/909f3fae50cad7095a92458e649f44f1de47105f/Telegram/SourceFiles/platform/linux/specific_linux.cpp#L323

So, we need to change "application name", why not to make it changeable from CMake? (https://github.com/procxx/kepka/issues/34)

**Comment by Hexawolf** [comment]
Or even let user configure that from settings?

**Comment by crackedmind** [comment]
Also connected to https://github.com/procxx/kepka/issues/20

**Comment by ghost** [comment]
Resolved by #82?

**Comment by ghost** [comment]
Yes, it is resolved by #82. :\
