### ISSUE TITLE
Don't switch to upstream client if it's already running

### ISSUE THREAD

**Issue by ghost** [procxx/tdesktop#76]
### Steps to reproduce
1. Launch upstream client
2. Launch kepka

### Expected behaviour
Kepka should start without trying to touch upstream client.

### Actual behaviour
Kepka brings up upstream client window and exits.

### Configuration
**Operating system:** Linux

**Version of Telegram Desktop:** latest commit from kepka, 1.2.6 from upstream

**Used theme**: irrelevant

**Comment by berkus** [comment]
Custom control socket for kepka should solve this.

**Comment by ghost** [comment]
Fixed by https://github.com/procxx/kepka/pull/77, forgot to close, sorry,

**Comment by berkus** [comment]
Cool!
