### ISSUE TITLE
Completely remove GTK dialogs and use Qt

### ISSUE THREAD

**Issue by xvitaly** [procxx/tdesktop#80]
Completely remove GTK open/save file dialogs and use Qt instead.

**Comment by crackedmind** [comment]
@xvitaly шустрый какой) там аппвейор еще не всепрожевал

**Comment by ghost** [comment]
Kepka uses Qt classes for these dialogs, Qt  uses native dialogs (GTK on Linux, if present, fallback to Qt's own otherwise). However, there is a way to force Qt's dialogs, but I see no reason for that.

**Comment by xvitaly** [comment]
@foxcpp We need to comletely drop this ugly GTK dialogs and always use Qt because this is a Qt application.
